#!/bin/bash

# Function to display usage information
usage() {
    echo "Usage: $0 [-r]"
    echo "  -r    run: run Discord after installation AND CLOSE TERMINAL"
    echo "  -s	  setup: move this script into /bin"
    exit 1
}

# Parse command-line options
option_r=0
option_s=0
while getopts ":r" opt; do
    case ${opt} in
        r )
            option_r=1
            ;;
        \? )
            usage
            ;;
    esac
done
shift $((OPTIND -1))

# Function to install Discord for Debian-based systems
install_deb() {
    wget "https://discord.com/api/download?platform=linux&format=deb" -O discord-current-version.deb
    sudo apt install -y ./discord-current-version.deb
    rm discord-current-version.deb
}

# Function to install Discord for Fedora-based systems
install_rpm() {
    wget "https://discord.com/api/download?platform=linux&format=rpm" -O discord-current-version.rpm
    sudo dnf install -y ./discord-current-version.rpm
    rm discord-current-version.rpm
}

# Detect the distribution and install accordingly
if [ -x "$(command -v apt)" ]; then
    # Debian-based
    install_deb
elif [ -x "$(command -v dnf)" ]; then
    # Fedora-based
    install_rpm
else
    echo "unsupported package manager"
    exit 1
fi

# Run Discord if -r was specified
if [ $option_r -eq 1]; then
    sudo mv udiscord /bin
elif [ $option_r -eq 1 ]; then
    discord &
    exit 0
fi

